site_name: Google Cloud Documentation Rewrite
theme:
  name: material
  features:
    # Allows copying code blocks
    - content.code.copy
    # Allows selecting code blocks
    - content.code.select
    # Shows the current path in the sidebar
    - navigation.path
    # Shows sections in the sidebar
    - navigation.sections
    # Shows sections expanded by default
    - navigation.expand
    # Enables annotations in code blocks
    - content.code.annotate
  palette:
    primary: black
  # logo: assets/logo.svg
  favicon: images/favicon-platform.svg

# repo_name: openai-agents-python
# repo_url: https://github.com/openai/openai-agents-python

plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: ["src/agents"]
  #         selection:
  #           docstring_style: google
  #         options:
  #           # Shows links to other members in signatures
  #           signature_crossrefs: true
  #           # Orders members by source order, rather than alphabetical
  #           members_order: source
  #           # Puts the signature on a separate line from the member name
  #           separate_signature: true
  #           # Shows type annotations in signatures
  #           show_signature_annotations: true
  #           # Makes the font sizes nicer
  #           heading_level: 3
  #           # Show inherited members
  #           inherited_members: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav:
            - Intro: example.md
            # - Quickstart: quickstart.md
            # - Examples: examples.md



extra:
  # Remove material generation message in footer
  generator: false
  language: en
  alternate:
    - name: English
      link: /openai-agents-python/
      lang: en
    # - name: 日本語
    #   link: /openai-agents-python/ja/
    #   lang: ja

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

extra_css:
  - stylesheets/extra.css

# watch:
#   - "src/agents"
